spring.application.name=Nowle-Api-Gateway

spring.servlet.multipart.max-file-size=20MB

spring.security.oauth2.client.registration.client2_development.client-id=sadada32ed
spring.security.oauth2.client.registration.client2_development.client-secret=dasdadad
spring.security.oauth2.client.registration.client2_development.scope=openid,profile
spring.security.oauth2.client.registration.client2_development.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.client2_development.redirect-uri=https://{FRONTEND-ADDRESS}/callback
spring.security.oauth2.client.registration.client2_development.client-authentication-method=client_secret_basic
spring.security.oauth2.client.provider.client2_development.authorization-uri=https://DOMAIN.auth.eu-north-1.amazoncognito.com/oauth2/authorize
spring.security.oauth2.client.provider.client2_development.token-uri=https://HOSTED_UI_DOMAIN.auth.eu-north-1.amazoncognito.com/oauth2/token
spring.security.oauth2.client.provider.client2_development.user-info-uri=https://HOSTED_UI_DOMAIN.auth.eu-north-1.amazoncognito.com/oauth2/userInfo
spring.security.oauth2.client.provider.client2_development.jwk-set-uri=https://cognito-idp.eu-north-1.amazonaws.com/eu-north-POOL_ID/.well-known/jwks.json
#logging.level.io.github.resilience4j=DEBUG

spring.security.oauth2.client.registration.client1.client-id=asdsadasdsd
spring.security.oauth2.client.registration.client1.client-secret=asdadasdasdasd
spring.security.oauth2.client.registration.client1.scope=openid,profile
spring.security.oauth2.client.registration.client1.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.client1.redirect-uri=https://{FRONTEND-ADDRESS}/callback
spring.security.oauth2.client.registration.client1.client-authentication-method=client_secret_basic
spring.security.oauth2.client.provider.client1.authorization-uri=https://DOMAIN.auth.eu-north-1.amazoncognito.com/oauth2/authorize
spring.security.oauth2.client.provider.client1.token-uri=https://HOSTED_UI_DOMAIN.auth.eu-north-1.amazoncognito.com/oauth2/token
spring.security.oauth2.client.provider.client1.user-info-uri=https://HOSTED_UI_DOMAIN.auth.eu-north-1.amazoncognito.com/oauth2/userInfo
spring.security.oauth2.client.provider.client1.jwk-set-uri=https://cognito-idp.eu-north-1.amazonaws.com/eu-north-POOL_ID/.well-known/jwks.json
#logging.level.io.github.resilience4j=DEBUG

aws.user.pool.id=

taget.micro.server.once.address=http://127.0.0.1
taget.micro.server.two.address=http://127.0.0.1
taget.micro.server.tree.address=http://127.0.0.1


spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.eu-north-1.amazonaws.com/eu-north-POOL_ID
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.eu-north-1.amazonaws.com/eu-north-POOL_ID/.well-known/jwks.json


logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG
#logging.level.reactor.core.publisher=DEBUG
management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=*
spring.cloud.gateway.metrics.enabled=true
management.endpoint.health.show-details=always


# TimeLimiter Configuration
resilience4j.timelimiter.instances.is-Server-Down--CircuitBreaker.timeoutDuration=5s
